defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: "plants"
    values:
      layout: 'plant'

collections:
  facts:
    output: false
  plants:
    output: true

title: Urban Wild