defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: "plants"
    values:
      layout: 'plant'

collections:
  instructions:
    output: false
  plants:
    output: true

title: Urban Wild

text_colors: 
  - dark
  - light